[workspace]
members = [
    "bridge/client",
    "bridge/cpi_poster",
    "bridge/program",
    "bridge/program_stub",
    "migration",
    "modules/nft_bridge/program",
    "modules/token_bridge/client",
    "modules/token_bridge/program",
    "solitaire/program",
    "solitaire/rocksalt",
]

