{
 "title": "Wormhole v2",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(wormhole_network_node_height, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Solana Slots/s",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(wormhole_solana_current_height{instance=~\"$instance\"}[$__rate_interval])"
    }
   ]
  },
  {
   "title": "Network Solana Height",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wormhole_network_node_height{instance=~\"$instance\", network=\"solana\"} > 0",
     "legendFormat": "{{ node_name }}"
    }
   ]
  },
  {
   "title": "Aggregation Cleanup State Machine",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(wormhole_aggregation_state_unobserved_total{instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "unobserved"
    },
    {
     "expr": "increase(wormhole_aggregation_state_expirations_total{instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "expirations"
    },
    {
     "expr": "increase(wormhole_aggregation_state_retries_total{instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "retries"
    },
    {
     "expr": "sum without (addr, origin, status)(increase(wormhole_aggregation_state_settled_signatures_total{instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "settled"
    },
    {
     "expr": "increase(wormhole_aggregation_state_timeout_total{instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "timeout"
    },
    {
     "expr": "increase(wormhole_aggregation_state_timeout_total{instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "timeout"
    }
   ]
  },
  {
   "title": "Aggregation State Size",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wormhole_aggregation_state_entries{instance=~\"$instance\"}",
     "legendFormat": "count"
    }
   ]
  },
  {
   "title": "Message Observations",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(wormhole_solana_observations_confirmed_total{instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "solana (confirmed)"
    }
   ]
  },
  {
   "title": "P2P Messages Received/s",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(wormhole_p2p_broadcast_messages_received_total{instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "title": "Watcher Error Count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(wormhole_solana_connection_errors_total{instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "[Solana] {{ reason }}"
    }
   ]
  },
  {
   "title": "Observations by Guardian",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(wormhole_observations_signed_by_guardian_total{instance=~\"$instance\", instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{ addr }}"
    }
   ]
  },
  {
   "title": "Missing Signatures",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(wormhole_aggregation_state_settled_signatures_total{status!=\"present\", instance=~\"$instance\"}[1h])",
     "legendFormat": "{{ addr }} [from {{ origin }}]"
    }
   ]
  },
  {
   "title": "Missing Signatures (except unknown)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(wormhole_aggregation_state_settled_signatures_total{status!=\"present\", origin!=\"unknown\", instance=~\"$instance\"}[1h])",
     "legendFormat": "{{ addr }} [from {{ origin }}]"
    }
   ]
  },
  {
   "title": "Solana Query Latency",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 58 },
   "targets": [
    {
     "expr": "sum(increase(wormhole_solana_query_latency_bucket{instance=~\"$instance\"}[$__interval])) by (le)"
    }
   ]
  }
 ]
}